<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-08-09">

<title>Multiple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="10d_MultipleLinearRegression_files/libs/clipboard/clipboard.min.js"></script>
<script src="10d_MultipleLinearRegression_files/libs/quarto-html/quarto.js"></script>
<script src="10d_MultipleLinearRegression_files/libs/quarto-html/popper.min.js"></script>
<script src="10d_MultipleLinearRegression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="10d_MultipleLinearRegression_files/libs/quarto-html/anchor.min.js"></script>
<link href="10d_MultipleLinearRegression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="10d_MultipleLinearRegression_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="10d_MultipleLinearRegression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="10d_MultipleLinearRegression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="10d_MultipleLinearRegression_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="10d_MultipleLinearRegression_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="10d_MultipleLinearRegression_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#simple-versus-multiple-linear-regression" id="toc-simple-versus-multiple-linear-regression" class="nav-link" data-scroll-target="#simple-versus-multiple-linear-regression">Simple Versus Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#training-and-test-data" id="toc-training-and-test-data" class="nav-link" data-scroll-target="#training-and-test-data">Training and Test Data</a></li>
  <li><a href="#eda-with-numerical-features" id="toc-eda-with-numerical-features" class="nav-link" data-scroll-target="#eda-with-numerical-features">EDA with Numerical Features</a></li>
  <li><a href="#building-a-multiple-linear-regression-model" id="toc-building-a-multiple-linear-regression-model" class="nav-link" data-scroll-target="#building-a-multiple-linear-regression-model">Building a Multiple Linear Regression Model</a></li>
  <li><a href="#assessing-our-fitted-model" id="toc-assessing-our-fitted-model" class="nav-link" data-scroll-target="#assessing-our-fitted-model">Assessing our Fitted Model</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="10d_MultipleLinearRegression.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multiple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 9, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<p>This notebook gives an overview of Multiple Linear Regression, where we’ll use more than one feature/predictor to predict a numerical response variable. After reviewing this notebook, you should be able to:</p>
<ul>
<li>Fit a multiple linear regression model to training data using <code>tidymodels</code></li>
<li>Assess that model’s performance on the training data by looking at global model utility metrics, and by analyzing metrics for the model term.</li>
<li>Interpret a multiple linear regression model with statistically significant predictors.</li>
<li>Use a multiple linear regression model to make predictions on new data.</li>
<li>Evaluate model performance on the test set.</li>
</ul>
<hr>
</section>
<section id="simple-versus-multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-versus-multiple-linear-regression">Simple Versus Multiple Linear Regression</h2>
<p>In the previous notebook, we learned that a simple linear regression model whose response variable is <span class="math inline">\(y\)</span> and whose sole predictor is <span class="math inline">\(x\)</span> is of the form <span class="math display">\[y = \beta_0 + \beta_1\cdot x +\varepsilon ~~~~\text{or}~~~~\mathbb{E}\left[y\right] = \beta_0 + \beta_1\cdot x\]</span></p>
<p>Multiple linear regression models are quite similar, the difference being that these multiple linear regression models contain multiple predictor variables: <span class="math inline">\(x_1,~x_2,~...~,x_k\)</span>. That is, these models take the form <span class="math display">\[y = \beta_0 + \beta_1\cdot x_1 + \beta_2\cdot x_2 + \cdots +\beta_k x_k +\varepsilon\]</span> <span class="math display">\[~~~~\text{--or--}~~~~\]</span> <span class="math display">\[\mathbb{E}\left[y\right] = \beta_0 + \beta_1\cdot x_1 + \beta_2\cdot x_2 + \cdots +\beta_k x_k\]</span></p>
<p>In a simple linear regression model, we could interpret the coefficient on the term containing the predictor variable as a <em>slope</em>. That is, the <span class="math inline">\(\beta\)</span> coefficient is the expected rate of change in the response variable per unit change in the predictor variable. For example, <em>a penguin whose bill is <span class="math inline">\(1\)</span>mm longer than average is expected to have about <span class="math inline">\(88.58\)</span>g more mass than the average penguin</em> or <em>for each additional millimeter of bill length, we expect a penguin to have about <span class="math inline">\(88.58\)</span>g more mass, on average</em>.</p>
<p>For multiple linear regression models, we have similar interpretations as long as the model terms are independent of one another (we’ll encounter scenarios where they are not when we look at higher-order terms later in our course). That is, the interpretation of <span class="math inline">\(\beta_i\)</span>, the coefficient on <span class="math inline">\(x_i\)</span> in our model is <em>the expected change in the response variable associated with a unit change in <span class="math inline">\(x_i\)</span>, while all other predictors are held constant</em>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Model Coefficients as Slopes
</div>
</div>
<div class="callout-body-container callout-body">
<p>For simple and multiple linear regression models where each model term contains a single numerical predictor, we can interpret the corresponding <span class="math inline">\(\beta\)</span>-coefficient as a slope, holding all other predictors constant.</p>
<p>That is, for the multiple linear regression model</p>
<p><span class="math display">\[\mathbb{E}\left[y\right] = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_k x_k\]</span> holding all other predictors constant, we expect a unit increase in <span class="math inline">\(x_i\)</span> to be associated with an increase of about <span class="math inline">\(\beta_i\)</span> in the expected value of <span class="math inline">\(y\)</span> as long as <span class="math inline">\(x_1\)</span> through <span class="math inline">\(x_k\)</span> are independent, numerical predictors.</p>
</div>
</div>
<p>Let’s move forward and see how to build, assess, and interpret a multiple linear regression model. For simplicity and continuity, we’ll continue working with the <code>palmerpenguins</code> data and try to predict <code>body_mass_g</code> using the other numerical <em>features</em> in the data set.</p>
<section id="training-and-test-data" class="level3">
<h3 class="anchored" data-anchor-id="training-and-test-data">Training and Test Data</h3>
<p>We’ll start by splitting our data into training and test sets, as usual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>penguin_splits <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(penguins)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>penguins_train <span class="ot">&lt;-</span> <span class="fu">training</span>(penguin_splits)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>penguins_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(penguin_splits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As a reminder, here’s the first few rows of our training data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">species</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">island</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bill_length_mm</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bill_depth_mm</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">flipper_length_mm</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">body_mass_g</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">44.5</td>
<td style="text-align: right;">14.3</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">4100</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2007</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">38.6</td>
<td style="text-align: right;">21.2</td>
<td style="text-align: right;">191</td>
<td style="text-align: right;">3800</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">2007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">Biscoe</td>
<td style="text-align: right;">45.3</td>
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">210</td>
<td style="text-align: right;">4300</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">2008</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">52.8</td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">205</td>
<td style="text-align: right;">4550</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">2008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">37.3</td>
<td style="text-align: right;">20.5</td>
<td style="text-align: right;">199</td>
<td style="text-align: right;">3775</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">2009</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">Dream</td>
<td style="text-align: right;">43.2</td>
<td style="text-align: right;">16.6</td>
<td style="text-align: right;">187</td>
<td style="text-align: right;">2900</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">2007</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="eda-with-numerical-features" class="level3">
<h3 class="anchored" data-anchor-id="eda-with-numerical-features">EDA with Numerical Features</h3>
<p>Let’s explore whether the numerical features in our data frame are <em>visually</em> associated with penguin body mass.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bill Length (mm)"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bill Depth (mm)"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Flipper Length (mm)"</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>(p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3)<span class="sc">/</span>p4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).
Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).
Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).
Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10d_MultipleLinearRegression_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It looks like there are positive associations between penguin body mass and the bill measurements as well as the flipper measurement. The plot with the year variable is difficult to read (which we’ll return to later) – for now, we’ll include the year variable in our model as another numerical predictor.</p>
</section>
<section id="building-a-multiple-linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="building-a-multiple-linear-regression-model">Building a Multiple Linear Regression Model</h3>
<p>The strategy for building a multiple linear regression model in <code>{tidymodels}</code> is exactly the same as the strategy for building a simple linear regression.</p>
<ul>
<li>Create a model <em>specification</em> using <code>linear_reg()</code> and set its fitting engine to <code>"lm"</code>.</li>
<li>Create a model <em>recipe</em> by passing the model formula and data to the <code>recipe()</code> function.</li>
<li>Package the model and recipe together into a <code>workflow()</code>.</li>
<li><em>Fit</em> the workflow by passing it to <code>fit()</code> with the training data.</li>
</ul>
<p>Let’s see that in action.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mass_multi_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>mass_multi_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> bill_length_mm <span class="sc">+</span> bill_depth_mm <span class="sc">+</span> flipper_length_mm <span class="sc">+</span> year, <span class="at">data =</span> penguins_train)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>mass_multi_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_multi_spec) <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_multi_rec)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="ot">&lt;-</span> mass_multi_wf <span class="sc">%&gt;%</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There it is – we have our model. Let’s check it out.</p>
</section>
<section id="assessing-our-fitted-model" class="level3">
<h3 class="anchored" data-anchor-id="assessing-our-fitted-model">Assessing our Fitted Model</h3>
<p>As a reminder, we’ll run several levels of assessment.</p>
<ul>
<li><p>A global model assessment (using <code>glance()</code>), including</p>
<ul>
<li>the <em>global test for model utility</em> (looking at the <code>p.value</code>)</li>
<li>an assessment of the proportion of variation in the response variable explained by our model (looking at the <code>adj.r.squared</code>)</li>
<li>understanding the expected “accuracy” of our model (looking at the <code>sigma</code> value, which measures the <em>residual standard error</em>, and constructing a naive confidence interval)</li>
</ul></li>
<li><p>Individual model-term analysis (using <code>fitted_model %&gt;% extract_fit_engine() %&gt;% tidy()</code>), including</p>
<ul>
<li>assessing the statistical significance of individual model terms (looking at the <code>p.value</code>s)</li>
<li>identifying and interpreting estimated model coefficients (looking at the <code>estimate</code>)</li>
<li>identifying and interpreting the uncertainty in these coefficient estimates (looking at the <code>std.error</code> to construct confidence intervals)</li>
</ul></li>
<li><p>An unbiased assessment of model performance</p>
<ul>
<li><p>Since the model knew the true body masses of the penguins that it is attempting to predict, it had an unfair advantage in predicting those values. Think of it this way, if you have a practice exam with an answer key (which you get to look at), then just because you do well on the practice exam doesn’t mean you are well-prepared for the real exam – the same holds true for the model.</p></li>
<li><p>We’ll use our model to make predictions for the body mass of penguins in our test data.</p></li>
<li><p>Once we have those questions, we’ll compute global model performance metrics like RMSE and R-Squared.</p>
<ul>
<li>Because the model didn’t know that these penguins existed, the model has no advantage in predicting their body mass. Assessing the model performance on these <em>test</em> penguins leaves the assessment unbiased.</li>
</ul></li>
</ul></li>
</ul>
<section id="global-model-assessment" class="level4">
<h4 class="anchored" data-anchor-id="global-model-assessment">Global Model Assessment</h4>
<p>Let’s use <code>glance()</code> to get some very high-level metrics about our overall model’s estimated performance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>, <span class="st">"striped"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7808404</td>
<td style="text-align: right;">0.7773478</td>
<td style="text-align: right;">387.1782</td>
<td style="text-align: right;">223.571</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-1886.198</td>
<td style="text-align: right;">3784.396</td>
<td style="text-align: right;">3805.667</td>
<td style="text-align: right;">37626655</td>
<td style="text-align: right;">251</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>First, we can conduct the <em>global test for model utility</em>. Since this is the first time we’ve really done such a test, a reminder of the hypotheses appears below. <span class="math display">\[\begin{array}{lcl} H_0 &amp; : &amp; \beta_1 = \beta_2 = \beta_3 = \beta_4 = 0\\
H_a &amp; : &amp; \text{At least one of the coefficients is non-zero}\end{array}\]</span></p>
<p>The <code>p.value</code> for this test is extremely small, so we have evidence to suggest that at least one of the model’s predictor terms has a non-zero coefficient. That’s good news – there is <em>atleast some</em> value to our model!</p>
<p>We can see from the <code>adj.r.squared</code> value that <em>approximately 77.73% of the variation in penguin body mass is explained by this model</em>.</p>
<p>Finally, we can assess the <em>residual standard error</em> (<code>sigma</code>) for the model. This value helps us estimate how accurate we should expect our predictions to be. At approximately 95% confidence, we can expect our predictions to be accurate to within about <span class="math inline">\(\pm\)</span> 774.36 grams. As a reminder, however, this estimate is biased and may be <em>too optimistic</em> about the errors our model will make in the future. We should recalculate this metric (and the adjusted R squared metric) using unseen data, such as the <em>test</em> data.</p>
</section>
<section id="assessment-of-individual-model-terms" class="level4">
<h4 class="anchored" data-anchor-id="assessment-of-individual-model-terms">Assessment of Individual Model Terms</h4>
<p>We’ll pipe our fitted model to <code>extract_fit_engine()</code> and <code>tidy()</code> to obtain the data frame of model terms and corresponding metrics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">232658.774875</td>
<td style="text-align: right;">60591.365347</td>
<td style="text-align: right;">3.8398008</td>
<td style="text-align: right;">0.0001560</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_length_mm</td>
<td style="text-align: right;">1.530334</td>
<td style="text-align: right;">5.984567</td>
<td style="text-align: right;">0.2557134</td>
<td style="text-align: right;">0.7983815</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bill_depth_mm</td>
<td style="text-align: right;">28.587515</td>
<td style="text-align: right;">15.997312</td>
<td style="text-align: right;">1.7870199</td>
<td style="text-align: right;">0.0751409</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">52.753150</td>
<td style="text-align: right;">2.783871</td>
<td style="text-align: right;">18.9495697</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">-119.323909</td>
<td style="text-align: right;">30.224297</td>
<td style="text-align: right;">-3.9479466</td>
<td style="text-align: right;">0.0001024</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The first thing we should do is look at the <code>p.value</code>s associated with the individual model terms. At this stage, if any model terms are not statistically significant we should remove them one-by-one. We’ll do so by removing the predictor with the highest <code>p.value</code> first.</p>
<p>Before we begin removing predictors from the model, perhaps this process seems a bit mysterious. It is worth looking at a visual of the estimated model coefficients and their plausible ranges.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">!=</span> <span class="st">"(Intercept)"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">y =</span> term, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xmin =</span> estimate <span class="sc">-</span> (<span class="dv">2</span><span class="sc">*</span>std.error), </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">xmax =</span> estimate <span class="sc">+</span> (<span class="dv">2</span><span class="sc">*</span>std.error),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">color =</span> term),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> term, <span class="at">color =</span> term),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Estimated Model Coefficient"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10d_MultipleLinearRegression_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that the plausible ranges for coefficients on <code>bill_length_mm</code> and <code>bill_depth_mm</code> overlap with <span class="math inline">\(0\)</span>. If these coefficients were <span class="math inline">\(0\)</span>, then the corresponding model terms would drop out of the model. This is what <em>statistical insignificance</em> means.</p>
<p>Let’s refit the model without the <code>bill_length_mm</code> predictor and see whether <code>bill_length_mm</code> should still be removed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mass_multi_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>mass_multi_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> bill_length_mm <span class="sc">+</span> flipper_length_mm <span class="sc">+</span> year, <span class="at">data =</span> penguins_train)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>mass_multi_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_multi_spec) <span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_multi_rec)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="ot">&lt;-</span> mass_multi_wf <span class="sc">%&gt;%</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">225991.977989</td>
<td style="text-align: right;">60739.032170</td>
<td style="text-align: right;">3.7207043</td>
<td style="text-align: right;">0.0002450</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_length_mm</td>
<td style="text-align: right;">3.794827</td>
<td style="text-align: right;">5.874269</td>
<td style="text-align: right;">0.6460083</td>
<td style="text-align: right;">0.5188618</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">49.895057</td>
<td style="text-align: right;">2.288486</td>
<td style="text-align: right;">21.8026532</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">-115.523634</td>
<td style="text-align: right;">30.280317</td>
<td style="text-align: right;">-3.8151395</td>
<td style="text-align: right;">0.0001713</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Bill length in millimeters is still just above the threshold for statistical significance. We’ll drop it from our model and refit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mass_multi_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>mass_multi_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> flipper_length_mm <span class="sc">+</span> year, <span class="at">data =</span> penguins_train)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>mass_multi_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_multi_spec) <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_multi_rec)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="ot">&lt;-</span> mass_multi_wf <span class="sc">%&gt;%</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>coef_df <span class="ot">&lt;-</span> mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>coef_df <span class="sc">%&gt;%</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">227916.26652</td>
<td style="text-align: right;">60596.048460</td>
<td style="text-align: right;">3.76124</td>
<td style="text-align: right;">0.0002101</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">1.712514</td>
<td style="text-align: right;">29.70736</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">-116.49701</td>
<td style="text-align: right;">30.207960</td>
<td style="text-align: right;">-3.85650</td>
<td style="text-align: right;">0.0001460</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Okay, both of the remaining predictors, <code>flipper_length_mm</code> and <code>year</code> are statistically significant. This gives us our “<em>final</em>” model form of <span class="math inline">\(\mathbb{E}\left[\text{body\_mass\_g}\right] = \beta_0 + \beta_1 \cdot\text{flipper\_length\_mm} + \beta_2\cdot\text{year}\)</span>, where the estimated model has <span class="math inline">\(\beta_0\approx\)</span> 227916.3, <span class="math inline">\(\beta_1\approx\)</span> 50.87, and <span class="math inline">\(\beta_2\approx\)</span> -116.5.</p>
<p>At this point, we have a model that we can make predictions and interpretations with. In terms of the model coefficients,</p>
<ul>
<li>We expect penguins with longer flippers to have greater mass. On average, with year being held constant, we expect a unit increase in flipper length to be associated with approximately <span class="math inline">\(50.87\)</span>g additional mass.</li>
<li>We expect penguins to have lower body mass with each passing year. On average, holding the flipper length constant, similar penguins from one year to the next are expected to have approximately <span class="math inline">\(116.5\)</span>g less body mass.</li>
</ul>
<section id="interpreting-marginal-effects-with-marginaleffects" class="level5">
<h5 class="anchored" data-anchor-id="interpreting-marginal-effects-with-marginaleffects">Interpreting Marginal Effects with <code>{marginaleffects}</code></h5>
<p>So far, we have been able to interpret each model coefficient as a slope. This is relatively straight forward. However, as we explore more complex models – particularly those with mixed effects and higher order terms – the interpretation of the impact of a predictor on the response is more difficult to extract. This is particularly true for those without a calculus background.</p>
<p>Fortunately, the <code>{marginaleffects}</code> package can help us. We’ll introduce it now because this is a simple case and this early exposure will make it easier for us to use the functionality later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>counterfactual_flipper_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">flipper_length_mm =</span> <span class="fu">seq</span>(<span class="dv">170</span>, <span class="dv">235</span>, <span class="at">length.out =</span> <span class="dv">500</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">year =</span> <span class="dv">2019</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>mfx <span class="ot">&lt;-</span> mass_multi_fit <span class="sc">%&gt;%</span> </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slopes</span>(<span class="at">newdata =</span> counterfactual_flipper_df,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">variables =</span> <span class="st">"flipper_length_mm"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">conf_level =</span> <span class="fl">0.95</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>()</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>mfx <span class="sc">%&gt;%</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, flipper_length_mm, estimate, conf.low, conf.high, std.error) <span class="sc">%&gt;%</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="at">n =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">flipper_length_mm</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">170.0000</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">170.1303</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">170.2605</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">170.3908</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">170.5210</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">170.6513</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">170.7816</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">170.9118</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">171.0421</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">171.1723</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">47.51951</td>
<td style="text-align: right;">54.22906</td>
<td style="text-align: right;">1.71165</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mfx <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(flipper_length_mm, estimate, conf.low, conf.high) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> estimate), <span class="at">color =</span> <span class="st">"purple"</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">"grey"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Flipper Length (mm)"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Marginal Effect"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Marginal Effects of Unit Increase in Flipper Length"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="10d_MultipleLinearRegression_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Reading off of the graph, we can see that the estimated marginal effect of an increase of 1mm in flipper length is associated with an estimated increase of just under 50g, and that this expected increase is independent of the current flipper length. Furthermore, we can see that we are 95% confident that the marginal effect of a unit increase in flipper length on expected body mass is somewhere between 47.5g/mm and 54.25g/mm. These estimates agree with the values we calculated from the tabular output of the regression model above.</p>
</section>
</section>
<section id="returning-to-global-performance-metrics" class="level4">
<h4 class="anchored" data-anchor-id="returning-to-global-performance-metrics">Returning to Global Performance Metrics</h4>
<p>Since our model form has changed, we need to reassess our global model metrics. They will have all shifted.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>, <span class="st">"striped"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7776845</td>
<td style="text-align: right;">0.775927</td>
<td style="text-align: right;">388.4116</td>
<td style="text-align: right;">442.5111</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-1888.028</td>
<td style="text-align: right;">3784.056</td>
<td style="text-align: right;">3798.237</td>
<td style="text-align: right;">38168479</td>
<td style="text-align: right;">253</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>It is no surprise that our model as a whole still has a significant <code>p.value</code>. We removed those predictors which we we were not confident had non-zero coefficients.</p>
<p>Our <code>adj.r.squared</code> value has changed slightly, and our final model explains approximately 77.59% of the variability in penguin body mass.</p>
<p>Finally, our <em>residual standard error</em> has also changed slightly. We now expect our predictions to be accurate to within about <span class="math inline">\(\pm\)</span> 776.82g.</p>
</section>
<section id="assessing-model-performance-on-unseen-test-observations" class="level4">
<h4 class="anchored" data-anchor-id="assessing-model-performance-on-unseen-test-observations">Assessing Model Performance on Unseen (Test) Observations</h4>
<p>We recognize that the <code>adj.r.squared</code> and <em>residual standard error</em> estimates from the global model metrics may be too optimistic. Again, this is because these measures are associated with how well our model predicts the <em>training</em> observations, where the model knew the answers. We can reconstruct these metrics using the <em>test</em> data to obtain unbiased estimates of model performance. We’ll do the following:</p>
<ul>
<li>Create a set of metrics (using <code>metric_set()</code>) that we wish to use to evaluate our model.</li>
<li>Augment our test data set with a column of predictions of body mass coming from our model.</li>
<li>Evaluate our metrics by comparing the true responses (<code>body_mass_g</code>) to the predicted responses (<code>.pred</code>)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>my_metrics <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(penguins_test) <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">my_metrics</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>, <span class="st">"striped"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.metric</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">.estimator</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">376.6980462</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.7450228</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>We see that the R Squared value is slightly lower on the test data than it was on the training data. As a reminder, a lower R Squared value indicates that a lower proportion of the variation in the response is explained by our model – that is, the model performs slightly worse on the test data according to the R Squared metric.</p>
<p>Note that <em>root mean squared error</em> is comparable to the <em>residual standard error</em> (<code>sigma</code>), as it measures the average prediction error. Similarly, we see a slightly lower <code>rmse</code> on the test data than we saw on the training data. As a reminder, lower <code>rmse</code> indicates better predictive performance, so this model performs slightly <em>better</em> on the test data according to the <code>rmse</code> metric. More on this later in our course as well.</p>
<p><strong>A Note on Comparing Model Metrics:</strong> The <em>residual standard error</em> (<code>sigma</code>) from the <code>glance()</code> function and the <code>rmse</code> metric we’ve computed just now utilize slightly different formulas, so they aren’t directly comparable (particularly in cases with very small data). One thing we can do is to use <code>glance()</code> for the <em>global test of model utility</em> only (interpreting that <code>p.value</code>), and then we can compute <code>rsq</code> and <code>rmse</code> for both the training and test sets and compare those to one another.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>(mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(penguins_test) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">my_metrics</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">type =</span> <span class="st">"test"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    (mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">augment</span>(penguins_train) <span class="sc">%&gt;%</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>       <span class="fu">select</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>       <span class="fu">my_metrics</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>       <span class="fu">mutate</span>(<span class="at">type =</span> <span class="st">"train"</span>))</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> type, </span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">names_from =</span> .metric, </span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> .estimate) <span class="sc">%&gt;%</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>, <span class="st">"striped"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rmse</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rsq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">test</td>
<td style="text-align: right;">376.698</td>
<td style="text-align: right;">0.7450228</td>
</tr>
<tr class="even">
<td style="text-align: left;">train</td>
<td style="text-align: right;">386.129</td>
<td style="text-align: right;">0.7776845</td>
</tr>
</tbody>
</table>


</div>
</div>
<hr>
</section>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Okay, we’ve covered quite a bit in this notebook! Here’s a recap of the most important ideas.</p>
<ul>
<li><p>Multiple linear regressions are extensions of simple linear regression models, in which we have <em>multiple</em> model terms containing predictor variables.</p></li>
<li><p>A multiple linear regression model takes the form <span class="math inline">\(\mathbb{E}\left[y\right] = \beta_0 + \beta_1\cdot x_1 + \beta_2\cdot x_2 + \cdots + \beta_k x_k\)</span>, where <span class="math inline">\(y\)</span> is the response variable and <span class="math inline">\(x_1,~x_2,~\cdots,~x_k\)</span> are predictors.</p></li>
<li><p>The <span class="math inline">\(\beta_0\)</span> “coefficient” is the intercept for the model – the expected response if all predictor variables take on the value <span class="math inline">\(0\)</span>.</p></li>
<li><p>Each <span class="math inline">\(\beta_i\)</span> for <span class="math inline">\(i &gt; 0\)</span> can be interpreted as a <em>slope</em> coefficient for the corresponding model term, when all other predictors are held constant.</p></li>
<li><p>We run multiple levels of assessment on our models.</p>
<ul>
<li><p>We use <code>fitted_model %&gt;% glance()</code> to obtain the <code>p.value</code> associated with a <em>global test for model utility</em>. That is, we test the hypotheses <span class="math display">\[\begin{array}{lcl} H_0 &amp; : &amp; \beta_1 = \beta_2 = \cdots = \beta_k = 0\\ H_a &amp; : &amp; \text{At least one of the model coefficients is non-zero}\end{array}\]</span></p></li>
<li><p>We use <code>fitted_model %&gt;% extract_fit_engine() %&gt;% tidy()</code> to obtain estimated model coefficients and diagnostics.</p>
<ul>
<li>In general, we look to the <code>p.value</code> column to determine whether model terms are statistically significant or not.</li>
<li>In the case where model terms are not statistically significant, we remove one predictor at a time (according to the highest <code>p.value</code>), and refit the model. We continue in this fashion until all remaining terms are statistically significant.</li>
<li>At this point, we have an estimated model and we can construct it using the estimated <span class="math inline">\(\beta\)</span> coefficients found in the <code>estimate</code> column.</li>
<li>The corresponding values in the <code>std.error</code> column help us build confidence intervals for the <span class="math inline">\(\beta\)</span> coefficients, giving us greater understanding of the uncertainty in our model.</li>
</ul></li>
<li><p>Finally, we can compute performance metrics for our model on both the <em>training</em> and <em>test</em> data sets.</p>
<ul>
<li>In general, we should expect our models to perform better on <em>training</em> data (since the model has access to the true responses during the fitting process), however this is not always the case.</li>
<li>Comparing these <em>training</em> and <em>test</em> metrics is a great way to gain insight into the current <em>fit</em> of our model and how we might be able to improve it. (More on this idea later in our course)</li>
</ul></li>
</ul></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>