<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-07-31">

<title>Introductory Statistics Review</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="8d_IntroStatsForRegression_Review_files/libs/clipboard/clipboard.min.js"></script>
<script src="8d_IntroStatsForRegression_Review_files/libs/quarto-html/quarto.js"></script>
<script src="8d_IntroStatsForRegression_Review_files/libs/quarto-html/popper.min.js"></script>
<script src="8d_IntroStatsForRegression_Review_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="8d_IntroStatsForRegression_Review_files/libs/quarto-html/anchor.min.js"></script>
<link href="8d_IntroStatsForRegression_Review_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="8d_IntroStatsForRegression_Review_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="8d_IntroStatsForRegression_Review_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="8d_IntroStatsForRegression_Review_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="8d_IntroStatsForRegression_Review_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="8d_IntroStatsForRegression_Review_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="8d_IntroStatsForRegression_Review_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link active" data-scroll-target="#confidence-intervals">Confidence Intervals</a></li>
  <li><a href="#hypothesis-tests" id="toc-hypothesis-tests" class="nav-link" data-scroll-target="#hypothesis-tests">Hypothesis Tests</a></li>
  <li><a href="#simple-regression-models-and-the-big-idea" id="toc-simple-regression-models-and-the-big-idea" class="nav-link" data-scroll-target="#simple-regression-models-and-the-big-idea">Simple Regression Models and “The Big Idea”</a>
  <ul class="collapse">
  <li><a href="#reading-regression-output" id="toc-reading-regression-output" class="nav-link" data-scroll-target="#reading-regression-output">Reading Regression Output</a></li>
  </ul></li>
  <li><a href="#multiple-regression-models" id="toc-multiple-regression-models" class="nav-link" data-scroll-target="#multiple-regression-models">Multiple Regression Models</a></li>
  <li><a href="#regression-assumptions-and-process" id="toc-regression-assumptions-and-process" class="nav-link" data-scroll-target="#regression-assumptions-and-process">Regression: Assumptions and Process</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introductory Statistics Review</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 31, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h2>
<p><strong>Confidence Intervals</strong>: Confidence intervals are used to capture a population parameter (population mean, population proportion, etc.) with some chosen degree of confidence. The general form for a confidence interval is given by: <span class="math display">\[\left(\text{point estimate}\right)\pm\left(\text{critical value}\right)\left(\text{standard error}\right)\]</span></p>
<ul>
<li>The <em>point estimate</em> is the sample statistic (sample mean, sample proportion, etc.) corresponding to the desired population parameter.</li>
<li>The <em>critical value</em> is determined by the desired confidence level.</li>
<li>The <em>standard error</em> is a measure quantifying variability in the estimate.</li>
</ul>
<p><strong>Approximate 95% Confidence Interval</strong>: We’ll often use an approximate 95% confidence interval. In this case we replace the critical value by 2, so the form is given by: <span class="math display">\[\left(\text{point estimate}\right)\pm 2\left(\text{standard error}\right)\]</span> We can interpret the interval by stating: “We are about 95% confident that [population parameter] is between [lower bound] and [upper bound].”</p>
<p><strong>An Example</strong>: A study to determine whether the appearance of adverse side effects from a drug is dependent on gender looked at the frequency of these side effects appearing in males and females. A point estimate for the difference in proportions (<span class="math inline">\(p_{males} - p_{females}\)</span>) resulted in a point estimate of <span class="math inline">\(0.075\)</span> with a standard error of <span class="math inline">\(0.04\)</span>. Use an approximate 95% confidence interval to determine if there is evidence to suggest that negative side effects from this drug occur more often in males.</p>
</section>
<section id="hypothesis-tests" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-tests">Hypothesis Tests</h2>
<strong>Hypothesis Testing:</strong> A hypothesis test is a method for testing statements about population parameters. Our hypotheses typically will look like one of the following:
<center>
<span class="math inline">\(\begin{array}{ll} H_0: &amp; \beta_1 = \beta_2 = ... = \beta_k = 0\\ H_a: &amp; \text{at least one }\beta_i\text{ is non-zero}\end{array} \hspace{1in} \begin{array}{ll} H_0: &amp; \beta_i=0\\ H_a: &amp; \beta_i\neq 0\end{array}\)</span>
</center>
<p>The hypotheses on the left reflect a <em>Global Test for Model Utility</em> (to determine whether the model has any utility at all), while the hypotheses on the right reflect <em>tests for significance of individual predictors</em>. The result of a hypothesis test depends on a <em>p</em>-value. If <span class="math inline">\(p &lt; \alpha\)</span>, then we reject <span class="math inline">\(H_0\)</span> and accept <span class="math inline">\(H_a\)</span>. If <span class="math inline">\(p\geq \alpha\)</span>, then we do not have enough evidence to reject <span class="math inline">\(H_0\)</span>. We usually use <span class="math inline">\(\alpha=.05\)</span>, but we can set different thresholds for different applications.</p>
<p>For us, rejecting the null hypothesis will typically mean that a model, or particular predictor, has some value.</p>
<p><strong>Example I</strong>: A model is built to predict <code>salary</code> of city workers given <code>years of service</code>. The hypothesized model assumes a linear relationship between the response and predictor. That is, <span class="math inline">\(\mathbb{E}\left[salary\right]=\beta_0+\beta_1\cdot\left(years~of~service\right)\)</span>. The <span class="math inline">\(p\)</span>-value reported for a global test of model utility was <span class="math inline">\(0.003\)</span>. Write the hypotheses for the test and determine the conclusion and its meaning.</p>
<p><strong>Example II</strong>: A more complex model to predict <code>salary</code> included many potential predictors. One such predictor was <code>years of education</code> (beyond high school). The estimated coefficient on this predictor was <span class="math inline">\(475\)</span> with a standard error of <span class="math inline">\(110\)</span>. Write the hypotheses involved in a test for the significance of this predictor and determine the result of the test. What does this mean?</p>
</section>
<section id="simple-regression-models-and-the-big-idea" class="level2">
<h2 class="anchored" data-anchor-id="simple-regression-models-and-the-big-idea">Simple Regression Models and “The Big Idea”</h2>
<p><strong>Definition (Simple Regression):</strong> A simple regression model is a model of the form <span class="math inline">\(\mathbb{E}\left[y\right]=\beta_0+\beta_1 x\)</span>, where <span class="math inline">\(y\)</span> is called the <em>response variable</em> and <span class="math inline">\(x\)</span> is a <em>predictor variable</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm, <span class="at">y =</span> body_mass_g), </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bill Depth (mm)"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Predicting Body Mass </span><span class="sc">\n</span><span class="st">with Bill Depth"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> body_mass_g), </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Flipper Length (mm)"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Predicting Body Mass </span><span class="sc">\n</span><span class="st">with Flipper Length"</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">/</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range (`stat_smooth()`).
Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="8d_IntroStatsForRegression_Review_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="reading-regression-output" class="level3">
<h3 class="anchored" data-anchor-id="reading-regression-output">Reading Regression Output</h3>
<p>Consider the simple regression output below for predicting selling <code>body_mass_g</code> of a penguin with <code>flipper_length_mm</code> as the sole predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mass_flipper_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>mass_flipper_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> flipper_length_mm, <span class="at">data =</span> penguins_train)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>mass_flipper_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_flipper_spec) <span class="sc">%&gt;%</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_flipper_rec)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>mass_flipper_fit <span class="ot">&lt;-</span> mass_flipper_wf <span class="sc">%&gt;%</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>mass_flipper_fit <span class="sc">%&gt;%</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7646157</td>
<td style="text-align: right;">0.763689</td>
<td style="text-align: right;">398.8774</td>
<td style="text-align: right;">825.0863</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-1895.34</td>
<td style="text-align: right;">3796.68</td>
<td style="text-align: right;">3807.315</td>
<td style="text-align: right;">40412211</td>
<td style="text-align: right;">254</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mass_flipper_fit <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-5768.75714</td>
<td style="text-align: right;">348.042020</td>
<td style="text-align: right;">-16.57489</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">49.67168</td>
<td style="text-align: right;">1.729255</td>
<td style="text-align: right;">28.72431</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<strong>Testing For Model Utility:</strong> Proposed form of the model,
<center>
<span class="math inline">\(\mathbb{E}\left[\text{body_mass}\right]=\beta_0+\beta_1\cdot\text{flipper_length}\)</span>
</center>
The hypotheses for a global test of model utility are as follows:
<center>
<span class="math inline">\(\begin{array}{ll} H_0:&amp; \beta_1=0\\ H_a: &amp; \beta_1\neq 0\end{array}\)</span> or <span class="math inline">\(\begin{array}{ll} H_0:&amp; \text{Flipper length is not a significant predictor of price}\\ H_a: &amp; \text{Flipper length is a significant predictor of price}\end{array}\)</span>
</center>
<p>We can find the <span class="math inline">\(p\)</span>-value given for the model as a whole from the results of <code>glance()</code> on our fitted model. That <span class="math inline">\(p\)</span>-value is <span class="math inline">\(9.388e-82\)</span> (that’s really small!), and so we reject <span class="math inline">\(H_0\)</span>, and claim that our model is useful. We won’t always <code>glance()</code> at our models, but doing so can be really helpful, especially in the case where you are suspicious of coefficients and <span class="math inline">\(p\)</span>-values for your individual predictors.</p>
<p><strong>Testing for Significance of Individual Predictors:</strong> Since we built a simple linear regression model, there is only one predictor. That means that the <em>global test of model utility</em> tested the same hypotheses as a test for significance of <code>flipper_length_mm</code> as an individual predictor. Notice that the <span class="math inline">\(p\)</span>-value for the <em>global test of model utility</em> matches the <span class="math inline">\(p\)</span>-value associated with the <code>flipper_length_mm</code> predictor. This won’t be the case once we begin adding more predictors to our models.</p>
<strong>Using and Interpreting a Model:</strong> Since our model to predict the body mass of a penguin depending on the length of the penguin’s flipper was significant, let’s use it! Note that the model we computed is:
<center>
<span class="math inline">\(\mathbb{E}\left[\text{price}\right]=-5768.76 + 49.67\cdot \text{flipper_length_mm}\)</span>
</center>
<ol type="1">
<li>Estimate the body mass for a penguin whose <code>flipper_length_mm</code> is <span class="math inline">\(200\)</span>mm.</li>
<li>Interpret the intercept for the model, and comment on whether or not it makes sense.</li>
<li>Give an interpretation of the coefficient on <code>flipper_length_mm</code>.</li>
</ol>
<p>What if we wanted to use more than one predictor simultaneously to predict body mass? Could we find a “better” model?</p>
</section>
</section>
<section id="multiple-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-models">Multiple Regression Models</h2>
<p><strong>Definition (Multiple Regression Models):</strong> Regression models that include more than one independent (<em>predictor</em>) variable are called multiple regression models.</p>
<strong>Definition (General Form for a Multiple Regression Model):</strong>
<center>
<span class="math inline">\(y=\beta_0+\beta_1x_1+\beta_2x_2+\cdots+\beta_kx_k+\varepsilon\)</span>
</center>
where <span class="math inline">\(y\)</span> is the dependent (<em>response</em>) variable, while <span class="math inline">\(x_1,\ldots ,x_k\)</span> are the independent (<em>predictor</em>) variables. The model which omits the error term,
<center>
<span class="math inline">\(\mathbb{E}\left[y\right]=\beta_0+\beta_1x_1+\beta_2x_2+\cdots+\beta_kx_k\)</span>
</center>
<p>is called the <em>deterministic</em> portion of the model. We will work exclusively with the deterministic portion of the model throughout much this course.</p>
<p>Note that in the general form of the multiple regression model, we may include higher order terms (like <span class="math inline">\(x_i^2\)</span>), or mixed terms (like <span class="math inline">\(x_ix_j\)</span>), or even terms for qualitative predictors! Models that include higher-order or interaction terms still fall under the category of <em>linear</em> regression. We’ll consider these terms later in our course.</p>
<p>Consider the regression output below for a model which predicts the body mass of a penguin given several of the numerical predictors available in the <code>penguins</code> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mass_multi_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>mass_multi_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> bill_length_mm <span class="sc">+</span> bill_depth_mm <span class="sc">+</span> flipper_length_mm <span class="sc">+</span> year, <span class="at">data =</span> penguins_train)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>mass_multi_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_multi_spec) <span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_multi_rec)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="ot">&lt;-</span> mass_multi_wf <span class="sc">%&gt;%</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7808404</td>
<td style="text-align: right;">0.7773478</td>
<td style="text-align: right;">387.1782</td>
<td style="text-align: right;">223.571</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-1886.198</td>
<td style="text-align: right;">3784.396</td>
<td style="text-align: right;">3805.667</td>
<td style="text-align: right;">37626655</td>
<td style="text-align: right;">251</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">232658.774875</td>
<td style="text-align: right;">60591.365347</td>
<td style="text-align: right;">3.8398008</td>
<td style="text-align: right;">0.0001560</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_length_mm</td>
<td style="text-align: right;">1.530334</td>
<td style="text-align: right;">5.984567</td>
<td style="text-align: right;">0.2557134</td>
<td style="text-align: right;">0.7983815</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bill_depth_mm</td>
<td style="text-align: right;">28.587515</td>
<td style="text-align: right;">15.997312</td>
<td style="text-align: right;">1.7870199</td>
<td style="text-align: right;">0.0751409</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">52.753150</td>
<td style="text-align: right;">2.783871</td>
<td style="text-align: right;">18.9495697</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">-119.323909</td>
<td style="text-align: right;">30.224297</td>
<td style="text-align: right;">-3.9479466</td>
<td style="text-align: right;">0.0001024</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Analyzing Multiple Regression Results:</strong> We would like to analyze our models on two levels: (i) global model metrics, and (ii) efficacy/significance of individual predictors and model terms. We can obtain global measures of model performance by piping our fitted model to <code>glance()</code>, while we can obtain measures related to individual model terms by piping our fitted model to <code>extract_fit_engine()</code> and <code>tidy()</code>. We’ll go through the results below.</p>
<ul>
<li><p>Global Model Metrics with <code>mass_multi_fit %&gt;% glance()</code></p>
<ul>
<li><p>The <code>r.squared</code> and <code>adj.r.squared</code> values are used to evaluate the <em>proportion of variation in the response variable which is explained by our model</em>. We use <code>r.squared</code> when dealing with <em>simple regression</em>, and <code>adj.r.squared</code> for <em>multiple regression</em>.</p></li>
<li><p>The <code>r.squared</code> and <code>adj.r.squared</code> values are measures of model fit, for which values closer to <span class="math inline">\(1\)</span> are better.</p></li>
<li><p>We should be suspicious of values too close to <span class="math inline">\(1\)</span> though!</p></li>
<li><p>The <code>sigma</code> value is the residual standard error for our model. It is related to the standard error of the prediction errors our model makes.</p>
<ul>
<li>The <code>sigma</code> value is a measure of model fit, for which lower values are better.</li>
<li>We can use <code>sigma</code> to build approximate confidence intervals for our model’s predictions. We can say that we expect our model’s predictions to be accurate to within about <span class="math inline">\(\pm 2\)</span><code>sigma</code>. We’ll see better ways to build these intervals though.</li>
</ul></li>
<li><p>The <code>statistic</code> and <code>p.value</code> are the computed test statistic and <span class="math inline">\(p\)</span>-value for our global test for model utility. $$</p>
<span class="math display">\[\begin{array}{lcl} H_0 &amp; : &amp; \beta_1 = \beta_2 = \beta_3 = \beta_4 = 0\\
H_a &amp; : &amp; \text{At least one of the coefficients is not 0}\end{array}\]</span></li>
<li><p>The <code>logLik</code>, <code>AIC</code>, <code>BIC</code>, and <code>deviance</code> are alternative measures of model significance, based in <em>information theory</em>. We won’t utilize these metrics.</p></li>
<li><p>The <code>df.residual</code> is the number of observations which are utilized to estimate the residual standard error (<code>sigma</code>). The <code>df</code> earlier in the table is the number of <span class="math inline">\(\beta\)</span> coefficients attached to variable terms in your model.</p></li>
<li><p>The <code>nobs</code> column indicates the <em>number of observations</em> used to fit your model.</p></li>
<li><p><strong>Note:</strong> When we run these global analyses, we’ll care most about <code>adj.r.squared</code>, <code>sigma</code>, <code>p.value</code>, and <code>df.residuals</code>.</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">232658.774875</td>
<td style="text-align: right;">60591.365347</td>
<td style="text-align: right;">3.8398008</td>
<td style="text-align: right;">0.0001560</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_length_mm</td>
<td style="text-align: right;">1.530334</td>
<td style="text-align: right;">5.984567</td>
<td style="text-align: right;">0.2557134</td>
<td style="text-align: right;">0.7983815</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bill_depth_mm</td>
<td style="text-align: right;">28.587515</td>
<td style="text-align: right;">15.997312</td>
<td style="text-align: right;">1.7870199</td>
<td style="text-align: right;">0.0751409</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">52.753150</td>
<td style="text-align: right;">2.783871</td>
<td style="text-align: right;">18.9495697</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">-119.323909</td>
<td style="text-align: right;">30.224297</td>
<td style="text-align: right;">-3.9479466</td>
<td style="text-align: right;">0.0001024</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li><p>Model Term Metrics with <code>mass_multi_fit %&gt;% extract_fit_engine() %&gt;% tidy()</code></p>
<ul>
<li><p>The <code>term</code> column describes the term in our model – here the individual predictors.</p></li>
<li><p>The <code>estimate</code> gives the estimated <span class="math inline">\(\beta\)</span> coefficient from the model-fitting process.</p></li>
<li><p>The <code>std.error</code> column gives the standard errors on the <span class="math inline">\(\beta\)</span> estimates. This is useful for constructing confidence intervals for your estimates or for identifying <em>problems</em> with the regression.</p></li>
<li><p>The <code>statistic</code> column gives the test statistic for a hypothesis test of the form</p>
<center>
<p><span class="math inline">\(\begin{array}{ll} H_0: &amp; \beta_i=0\\ H_a: &amp; \beta_i\neq 0\end{array}\)</span></p>
</center>
<p>where <span class="math inline">\(\beta_i\)</span> is the coefficient attached to the corresponding predictor.</p></li>
<li><p>The <code>p.value</code> column gives the <span class="math inline">\(p\)</span>-value for the test mentioned above.</p></li>
</ul></li>
</ul>
<p><strong>Completed Example:</strong> Consider the multiple regression output below for our multiple linear regression model which uses <code>bill_length_mm</code>, <code>bill_depth_mm</code>, <code>flipper_length_mm</code> and <code>year</code> to predict the <code>body_mass_g</code> of a penguin.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7808404</td>
<td style="text-align: right;">0.7773478</td>
<td style="text-align: right;">387.1782</td>
<td style="text-align: right;">223.571</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-1886.198</td>
<td style="text-align: right;">3784.396</td>
<td style="text-align: right;">3805.667</td>
<td style="text-align: right;">37626655</td>
<td style="text-align: right;">251</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">232658.774875</td>
<td style="text-align: right;">60591.365347</td>
<td style="text-align: right;">3.8398008</td>
<td style="text-align: right;">0.0001560</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_length_mm</td>
<td style="text-align: right;">1.530334</td>
<td style="text-align: right;">5.984567</td>
<td style="text-align: right;">0.2557134</td>
<td style="text-align: right;">0.7983815</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bill_depth_mm</td>
<td style="text-align: right;">28.587515</td>
<td style="text-align: right;">15.997312</td>
<td style="text-align: right;">1.7870199</td>
<td style="text-align: right;">0.0751409</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">52.753150</td>
<td style="text-align: right;">2.783871</td>
<td style="text-align: right;">18.9495697</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">-119.323909</td>
<td style="text-align: right;">30.224297</td>
<td style="text-align: right;">-3.9479466</td>
<td style="text-align: right;">0.0001024</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Analyzing the Regression Output:</strong> We evaluate the regression model using the steps below:</p>
<ul>
<li><p><em>Global Test for Overall Model Utility</em>: We test the hypotheses</p>
<center>
<p><span class="math inline">\(\begin{array}{ll} H_0: &amp; \beta_1=\beta_2=\beta_3=\beta_4=0\\ H_a: &amp; \text{At least one of the }\beta\text{'s is non-zero}\end{array}\)</span></p>
</center>
<p>Notice that the <span class="math inline">\(p\)</span>-value associated with this test is <span class="math inline">\(1.82e-81\)</span> (very small), and so we reject <span class="math inline">\(H_0\)</span>, and claim that our overall model has some significance.</p></li>
<li><p><em>Interpret Adjusted R-Squared</em>: Notice that the value of Adjusted R-squared is <span class="math inline">\(.777\)</span>. This tells us that approximately “<span class="math inline">\(77.7\%\)</span> of the variation in penguin <code>body_mass_g</code> is explained by our model.”</p>
<ul>
<li>Get comfortable with the form of the sentence in quotes above. We will use it quite often.</li>
<li>Notice that we are explaining <strong>variation</strong> in the response, <strong>not variance</strong>. In statistics, variance means something very specific.</li>
</ul></li>
<li><p><em>Test the significance of individual terms</em>: Here we test each individual term to determine whether it contributes significantly to the model, or if it should be a candidate for dropping from the model. In general, we use many <span class="math inline">\(t\)</span>-tests here.</p>
<center>
<p><span class="math inline">\(\begin{array}{ll} H_0: &amp; \beta_i=0\\ H_a: &amp; \beta_i\neq 0\end{array}\)</span></p>
</center>
<p>notice that the <span class="math inline">\(p\)</span>-values associated with <code>bill_length_mm</code> and <code>bill_depth_mm</code> are not significant (they exceed <span class="math inline">\(0.05\)</span>). Since this is the case, we’ll drop the predictor corresponding to the highest <span class="math inline">\(p\)</span>-value and re-fit our model. This procedure is called <em>backward elimination</em>.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mass_multi_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>mass_multi_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> bill_depth_mm <span class="sc">+</span> flipper_length_mm <span class="sc">+</span> year, <span class="at">data =</span> penguins_train)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>mass_multi_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_multi_spec) <span class="sc">%&gt;%</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_multi_rec)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="ot">&lt;-</span> mass_multi_wf <span class="sc">%&gt;%</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7807833</td>
<td style="text-align: right;">0.7781736</td>
<td style="text-align: right;">386.4596</td>
<td style="text-align: right;">299.1825</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1886.231</td>
<td style="text-align: right;">3782.463</td>
<td style="text-align: right;">3800.189</td>
<td style="text-align: right;">37636458</td>
<td style="text-align: right;">252</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">233601.98715</td>
<td style="text-align: right;">60366.73367</td>
<td style="text-align: right;">3.869714</td>
<td style="text-align: right;">0.0001388</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_depth_mm</td>
<td style="text-align: right;">29.45370</td>
<td style="text-align: right;">15.60556</td>
<td style="text-align: right;">1.887385</td>
<td style="text-align: right;">0.0602578</td>
</tr>
<tr class="odd">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">53.21694</td>
<td style="text-align: right;">2.10806</td>
<td style="text-align: right;">25.244509</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">-119.81399</td>
<td style="text-align: right;">30.10749</td>
<td style="text-align: right;">-3.979541</td>
<td style="text-align: right;">0.0000903</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Our new model has a slightly improved <code>adj.r.squared</code> value. This estimate tells us that “<em>approximately 77.8% of the variation in penguin body mass is explained by our model</em>”. The <span class="math inline">\(p\)</span>-value for the global test of model utility has remained significant as well. Now, looking at the model term metrics, we see that the <span class="math inline">\(p\)</span>-value for <code>bill_depth_mm</code> has remained insignificant while all the other predictors are statistically significant, so we’ll drop it as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mass_multi_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>mass_multi_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> flipper_length_mm <span class="sc">+</span> year, <span class="at">data =</span> penguins_train)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>mass_multi_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_multi_spec) <span class="sc">%&gt;%</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_multi_rec)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="ot">&lt;-</span> mass_multi_wf <span class="sc">%&gt;%</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7776845</td>
<td style="text-align: right;">0.775927</td>
<td style="text-align: right;">388.4116</td>
<td style="text-align: right;">442.5111</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-1888.028</td>
<td style="text-align: right;">3784.056</td>
<td style="text-align: right;">3798.237</td>
<td style="text-align: right;">38168479</td>
<td style="text-align: right;">253</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mass_multi_fit <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">227916.26652</td>
<td style="text-align: right;">60596.048460</td>
<td style="text-align: right;">3.76124</td>
<td style="text-align: right;">0.0002101</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">50.87429</td>
<td style="text-align: right;">1.712514</td>
<td style="text-align: right;">29.70736</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">-116.49701</td>
<td style="text-align: right;">30.207960</td>
<td style="text-align: right;">-3.85650</td>
<td style="text-align: right;">0.0001460</td>
</tr>
</tbody>
</table>


</div>
</div>
Now that all of the model terms are statistically significant, we can consider this our “final” model. From the output, we can see that this “final” model is of the form:
<center>
<span class="math inline">\(\mathbb{E}\left[y\right] = 227916.27 + 50.87\cdot \text{flipper_length} - 116.5\cdot \text{year}\)</span>
</center>
<ol type="1">
<li><p>What is the expected body mass (in grams) for a penguin whose flipper length is 200mm and which was observed in the year 2017?</p></li>
<li><p>To within approximately how many grams should we expect our predictions to be accurate? (Use 95% unless otherwise requested)</p></li>
<li><p>Find an interval which is “likely” to contain the body mass of a penguin whose flipper length is 200mm in the year 2017.</p></li>
</ol>
<p><strong>Remark:</strong> If a predictor variable <span class="math inline">\(x_i\)</span> is dropped from a model, there are three possibilities:</p>
<ul>
<li>There is no relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x_i\)</span></li>
<li>A linear relationship exists, but a Type II error occurred</li>
<li>A relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x_i\)</span> exists but it is not linear</li>
</ul>
</section>
<section id="regression-assumptions-and-process" class="level2">
<h2 class="anchored" data-anchor-id="regression-assumptions-and-process">Regression: Assumptions and Process</h2>
<p><strong>Assumptions:</strong> Consider that you have a dataset of the form <span class="math inline">\(\left(y,x_1,x_2,\cdots,x_k\right)\)</span> (think of an Excel table with these column headers), and a final regression model of the form <span class="math inline">\(\mathbb{E}\left[y\right]=\beta_0+\beta_1x_1+\cdots+\beta_kx_k\)</span> (other terms are possible). Then, we have the following assumptions required for making inferences with our model:</p>
<ul>
<li>Individual predictor variables are independet of one-another</li>
<li>Given values of <span class="math inline">\(x_1,x_2,\cdots,x_k\)</span>, the error term <span class="math inline">\(\varepsilon \sim N\left(0,\sigma\right)\)</span></li>
<li>The random errors are independent of one another</li>
</ul>
<p>There are also some others that we will discuss later in the course.</p>
<p><strong>Process:</strong> It might be helpful to see where our class sits in the statistical modeling process. Below is a short outline of the statistical modeling process.</p>
<ul>
<li>Identify a question or problem which has inherent uncertainty and for which building a model makes sense</li>
<li>Collect, find, or synthesize data</li>
<li>Clean the data (datasets can be very messy)</li>
<li>Explore the data (basic summary statistics, plots, etc.)</li>
<li>Hypothesize the form of your regression model</li>
<li>Create an initial model or models</li>
<li>Refine the models</li>
<li>Check assumptions</li>
<li>Interpret and use the model (make inferences)</li>
<li>Check for reproducibility</li>
</ul>
<p>We’ll be engaged in all of these aspects of the statistical modeling process except for data collection and checking for reproducibility. Additionally, since we’ll be using existing and publicly available data sets, we’ll be limited in the types of questions we can ask.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>