<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-08-03">

<title>Simple Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="9d_SimpleLinearRegression_files/libs/clipboard/clipboard.min.js"></script>
<script src="9d_SimpleLinearRegression_files/libs/quarto-html/quarto.js"></script>
<script src="9d_SimpleLinearRegression_files/libs/quarto-html/popper.min.js"></script>
<script src="9d_SimpleLinearRegression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="9d_SimpleLinearRegression_files/libs/quarto-html/anchor.min.js"></script>
<link href="9d_SimpleLinearRegression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="9d_SimpleLinearRegression_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="9d_SimpleLinearRegression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="9d_SimpleLinearRegression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="9d_SimpleLinearRegression_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="9d_SimpleLinearRegression_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="9d_SimpleLinearRegression_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#initial-exploration" id="toc-initial-exploration" class="nav-link" data-scroll-target="#initial-exploration">Initial Exploration</a></li>
  <li><a href="#build-our-models" id="toc-build-our-models" class="nav-link" data-scroll-target="#build-our-models">Build our Models</a></li>
  <li><a href="#assessing-model-utility" id="toc-assessing-model-utility" class="nav-link" data-scroll-target="#assessing-model-utility">Assessing Model Utility</a></li>
  <li><a href="#interpreting-our-models" id="toc-interpreting-our-models" class="nav-link" data-scroll-target="#interpreting-our-models">Interpreting Our Models</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="9d_SimpleLinearRegression.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simple Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 3, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<p>This notebook gives an overview of Simple Linear Regression, where we’ll use a single predictor to predict a numerical response variable. After reviewing this notebook, you should be able to:</p>
<ul>
<li>Fit a simple linear regression model to training data using <code>tidymodels</code></li>
<li>Assess that model’s performance on the training data by looking at global model utility metrics, and by analyzing metrics for the model term.</li>
<li>Interpret a simple linear regression model with a statistically significant predictor.</li>
<li>Use a simple linear regression model to make predictions on new data.</li>
<li>Evaluate model performance on the test set.</li>
</ul>
<hr>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple Linear Regression</h2>
<p>In building a simple linear regression model, we are making the claim that <span class="math inline">\(\text{response} = \beta_0 + \beta_1\cdot\text{predictor} + \varepsilon\)</span> or <span class="math inline">\(\mathbb{E}\left[\text{response}\right] = \beta_0 + \beta_1\cdot\text{predictor}\)</span>. That is, our predictor is the only useful variable in predicting our outcome (response), and that all other fluctuation in the response values are the result of random noise (<span class="math inline">\(\varepsilon\)</span>). This is not often the case, but simple linear regression models offer useful insights nonetheless.</p>
<p>In the previous notebook, we used <code>bill_length_mm</code> to predict <code>body_mass_g</code> for our penguins. Let’s return to the penguins data and build a couple of simple linear regression models. The first will use <code>bill_length_mm</code> to predict <code>body_mass_g</code>, but the second will use <code>flipper_length_mm</code> to predict <code>body_mass_g</code>. We’ll build, assess, and interpret both models.</p>
<section id="initial-exploration" class="level3">
<h3 class="anchored" data-anchor-id="initial-exploration">Initial Exploration</h3>
<p>We’ll start by splitting our data into training and test sets, as usual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>penguin_splits <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(penguins)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>penguins_train <span class="ot">&lt;-</span> <span class="fu">training</span>(penguin_splits)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>penguins_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(penguin_splits)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We know that we want to use <code>bill_length_mm</code> and <code>flipper_length_mm</code> to predict the body mass of our penguins. Let’s do some quick EDA to see if any potential relationships are visibly evident.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bill Length (mm)"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> penguins_train <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> flipper_length_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Flipper Length (mm)"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Body Mass (g)"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).
Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="9d_SimpleLinearRegression_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It seems like there are associations between <code>body_mass_g</code> and both <code>bill_length_mm</code> and <code>flipper_length_mm</code> individually. This gives us hope that our regression models will be statistically significant.</p>
</section>
<section id="build-our-models" class="level3">
<h3 class="anchored" data-anchor-id="build-our-models">Build our Models</h3>
<p>We’ll use our <code>{tidymodels}</code> framework to build our linear regression models. We’ll do the following for each model:</p>
<ul>
<li>Specify a linear regression model and set its engine.</li>
<li>Build a recipe including the appropriate model formula.</li>
<li>Package the model and recipe together into a workflow.</li>
<li>Fit the workflow to our training data.</li>
</ul>
<p>Let’s build and fit the model using <code>bill_length_mm</code> to predict <code>body_mass_g</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mass_bill_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>mass_bill_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> bill_length_mm, <span class="at">data =</span> penguins_train)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>mass_bill_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_bill_spec) <span class="sc">%&gt;%</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_bill_rec)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>mass_bill_fit <span class="ot">&lt;-</span> mass_bill_wf <span class="sc">%&gt;%</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we’ll build and fit the model using <code>flipper_length_mm</code> to predict <code>body_mass_g</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mass_flipper_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>mass_flipper_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> flipper_length_mm, <span class="at">data =</span> penguins_train)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>mass_flipper_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(mass_flipper_spec) <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(mass_flipper_rec)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>mass_flipper_fit <span class="ot">&lt;-</span> mass_flipper_wf <span class="sc">%&gt;%</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(penguins_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ve got our fitted models! We’ll assess the quality of the models in the next section.</p>
</section>
<section id="assessing-model-utility" class="level3">
<h3 class="anchored" data-anchor-id="assessing-model-utility">Assessing Model Utility</h3>
<p>We’ll engage in three levels of model assessment at this stage:</p>
<ul>
<li><p>Global assessment of model utility</p></li>
<li><p>Assessment of individual model terms</p></li>
<li><p>Model performance on unseen test data<span class="math inline">\(^*\)</span></p>
<ul>
<li>While we’ll look at how the model performs on unseen test data now, we generally would not do that at this stage. We want the test data to remain unseen until we have identified our <strong>final</strong> model.</li>
<li>More on this soon!</li>
</ul></li>
</ul>
<section id="global-assessments-of-model-utility" class="level4">
<h4 class="anchored" data-anchor-id="global-assessments-of-model-utility">Global Assessments of Model Utility</h4>
<p>We’ll pipe our fitted models to <code>glance()</code> and will assess our model using the <code>r.squared</code>, <code>sigma</code>, and <code>p.value</code> metrics. Let’s start with the model using <code>bill_length_mm</code> as the sole predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mass_bill_fit <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.3593701</td>
<td style="text-align: right;">0.3568479</td>
<td style="text-align: right;">658.043</td>
<td style="text-align: right;">142.4848</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-2023.498</td>
<td style="text-align: right;">4052.995</td>
<td style="text-align: right;">4063.631</td>
<td style="text-align: right;">109987231</td>
<td style="text-align: right;">254</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Firstly, we see that the <span class="math inline">\(p\)</span>-value for the overall model is very small. This indicates that our model has <em>some</em> utility in predicting/explaining penguin body mass. Since we are assessing a <em>simple</em> linear regression model, we’ll look at the <code>r.squared</code> value instead of <code>adj.r.squared</code>. From <code>r.squared</code>, we see that “<em>Approximately 35.94% of the variation in penguin body mass is explained by bill length</em>”. Finally, we see that the <em>residual standard error</em> (<code>sigma</code>) on the training data is about <span class="math inline">\(658\)</span>g. This residual standard error tells us that we should expect our predictions, on average, to be within about <span class="math inline">\(\pm 1,316\)</span>g.</p>
<p>Now let’s look at our model using <code>flipper_length_mm</code> as the sole predictor and see how it stacks up the bill length model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mass_flipper_fit <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glance</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">adj.r.squared</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sigma</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">logLik</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">BIC</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">deviance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df.residual</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7646157</td>
<td style="text-align: right;">0.763689</td>
<td style="text-align: right;">398.8774</td>
<td style="text-align: right;">825.0863</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-1895.34</td>
<td style="text-align: right;">3796.68</td>
<td style="text-align: right;">3807.315</td>
<td style="text-align: right;">40412211</td>
<td style="text-align: right;">254</td>
<td style="text-align: right;">256</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Our flipper length model is superior in every way! This model also has a statistically significant <span class="math inline">\(p\)</span>-value, indicating that it has some value in predicting/explaining penguin body mass. The <code>r.squared</code> value indicates that “<em>approximately 76.37% of the variation in penguin body mass is explained by our model</em>”. The <em>residual standard error</em> (<code>sigma</code>) indicates that we can expect this models predictions, on average, to be accurate to within about <span class="math inline">\(\pm 797\)</span>g.</p>
<p>Now let’s move to assessing the individual model terms.</p>
</section>
<section id="assessing-model-terms" class="level4">
<h4 class="anchored" data-anchor-id="assessing-model-terms">Assessing Model Terms</h4>
<p>We’ll now pipe our fitted models into <code>extract_fit_engine()</code> and <code>tidy()</code> to obtain metrics on the individual <span class="math inline">\(\beta\)</span> values (those individual terms containing predictor variables in our model). Again, let’s look at the model using <code>bill_length_mm</code> as the sole predictor first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mass_bill_fit <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">320.34582</td>
<td style="text-align: right;">327.84621</td>
<td style="text-align: right;">0.9771222</td>
<td style="text-align: right;">0.3294383</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_length_mm</td>
<td style="text-align: right;">88.57962</td>
<td style="text-align: right;">7.42078</td>
<td style="text-align: right;">11.9366986</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>From the data frame above, we have several takeaways. First, the fitted model is <span class="math inline">\(\mathbb{E}\left[\text{body\_mass\_g}\right] \approx 320.35 + 88.58\cdot\text{bill\_length\_mm}\)</span>. Since the <span class="math inline">\(p\)</span>-value on the <code>bill_length_mm</code> predictor is low, this indicates that <code>bill_length_mm</code> is a <em>statistically significant</em> predictor of <code>body_mass_g</code>. This means we can use this model to make predictions about the body mass of a new penguin (as long as we remain aware of the expected prediction error, <span class="math inline">\(\pm 2\)</span><code>sigma</code>), and we can also interpret the effect of <code>bill_length_mm</code> on <code>body_mass_g</code> (we’ll see this in the Model Interpretations section of this notebook). We shouldn’t overlook the <code>std.error</code> column. This gives us the standard error in the coefficient estimates. We can use that standard error to compute confidence intervals for the coefficient estimate – that is, <em>we can be about 95% certain that the coefficient on <code>bill_length_mm</code> is somewhere between <span class="math inline">\(88.58 - 2\left(7.42\right)\)</span> and <span class="math inline">\(88.58 + 2\left(7.42\right)\)</span></em>.</p>
<p>We can discover similar information about our model which uses <code>flipper_length_mm</code> as the sole predictor of penguin body mass.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mass_flipper_fit <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-5768.75714</td>
<td style="text-align: right;">348.042020</td>
<td style="text-align: right;">-16.57489</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">flipper_length_mm</td>
<td style="text-align: right;">49.67168</td>
<td style="text-align: right;">1.729255</td>
<td style="text-align: right;">28.72431</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>From here, we note that the <code>flipper_length_mm</code> model term is statistically significant, given the very small <span class="math inline">\(p\)</span>-value. The estimated model is <span class="math inline">\(\mathbb{E}\left[\text{body\_mass\_g}\right] \approx -5768.76 + 49.67\cdot\text{flipper\_length\_mm}\)</span>. Again, we can identify from the <code>std.error</code> column that <em>we are approximately 95% certain that the coefficient on <code>flipper_length_mm</code> is somewhere between about <span class="math inline">\(46.21\)</span> and <span class="math inline">\(53.13\)</span></em>.</p>
<p>We now have two separate models that we can utilize to predict penguin body mass as well as to interpret, in the case that we are interested in making inferential claims about how penguin <em>bill length</em> or <em>flipper length</em> is associated with penguin <em>body mass</em>. The global model metrics indicate that the model using <em>flipper length</em> to predict <em>body mass</em> is a better overall model.</p>
<p>How do we know that these models will perform well on new data?</p>
</section>
<section id="assessing-predictive-performance-on-unseen-test-data" class="level4">
<h4 class="anchored" data-anchor-id="assessing-predictive-performance-on-unseen-test-data">Assessing Predictive Performance on Unseen Test Data</h4>
<p>It could be the case that our models are just doing well on the data they were trained on and can’t be reliably utilized on new penguins. For this reason, the <em>residual standard error</em> (<code>sigma</code>) and <em>R squared</em> (<code>r.squared</code>) metrics from the <em>global model metrics</em> are biased estimates of model performance – the model had an unfair advantage on the training data; it knew all of the correct penguin body masses! This is the reason we’ve held out the <em>test</em> data. We can measure the models’ perfomances on the penguins in the test set to ensure that our models perform the way we expect. In fact, the metrics we compute on the <em>unseen</em> data are the ones we really should use as estimates for future model performance.</p>
<p>Let’s use our model to make predictions for the body masses of the penguins in the test data set. We’ll use those predictions to compute a <em>test RMSE</em> and a <em>test R Squared</em>. As a reminder, we’ll <code>augment()</code> our test data, adding a predictions (<code>.pred</code>) column, and then use the <code>rmse()</code> function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>my_metrics <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>mass_bill_fit <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(penguins_test) <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">my_metrics</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.metric</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">.estimator</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">607.0706520</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.3379565</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>The model using <code>bill_length_mm</code> as the sole predictor of <code>body_mass_g</code> seems to have done slightly better on the test set than it did on the training data. This is interesting and we’ll discuss it more in the coming weeks! For now, this output indicates that we should expect our model’s predictions to be accurate to within about <span class="math inline">\(\pm 1214\)</span>g.</p>
<p>Let’s look at how our other model performs on the unseen test data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>my_metrics <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(rmse, rsq)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>mass_flipper_fit <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(penguins_test) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">my_metrics</span>(body_mass_g, .pred) <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.metric</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">.estimator</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rmse</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">380.8203026</td>
</tr>
<tr class="even">
<td style="text-align: left;">rsq</td>
<td style="text-align: left;">standard</td>
<td style="text-align: right;">0.7405649</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Again, the model using <code>flipper_length_mm</code> to predict penguin body mass has performed slightly better than expected on the <em>test</em> data. Perhaps we’ve gotten an <em>easy</em> test set – we’ll need to find a better way to control for this! We want our performance estimates to be truly unbiased. While the model hadn’t seen these <em>test</em> penguins during the training process, it does seem that these penguins may be more “typical” than some of the penguins in the training set.</p>
</section>
</section>
<section id="interpreting-our-models" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-our-models">Interpreting Our Models</h3>
<p>It isn’t always the case that we are solely interested in prediction or predictive performance. Sometimes we are building models to <em>describe</em> associations or other phenomena. Linear regression models are particularly useful for this because they are <em>parametric</em> – we get a “slope” parameter for each of our model terms! We can interpret these slopes just as you’ve done in the past – as a rate of change – if our predictor variable increases, how do we expect our response variable to change.</p>
<p>In order to make these interpretations, let’s look back at the data frame containing our model terms. As a reminder, we pipe our fitted model into <code>extract_fit_engine()</code> and <code>tidy()</code> to get this output. As usual, we’ll work with the bill length model first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mass_bill_fit <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">320.34582</td>
<td style="text-align: right;">327.84621</td>
<td style="text-align: right;">0.9771222</td>
<td style="text-align: right;">0.3294383</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_length_mm</td>
<td style="text-align: right;">88.57962</td>
<td style="text-align: right;">7.42078</td>
<td style="text-align: right;">11.9366986</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>From the table above, we obtain our estimated model: <span class="math inline">\(\mathbb{E}\left[\text{body\_mass\_g}\right] \approx 320.35 + 88.58\cdot\text{bill\_length\_mm}\)</span>. From this model, we can see that the slope coefficient on <code>bill_length_mm</code> is positive, so longer bills are associated with more massive penguins. There are a couple of ways we can interpret the magnitude of the coefficient (the effect size) as well:</p>
<ul>
<li><strong>Using the Estimate:</strong> Given two penguins, one whose bill length is one millimeter longer than the other, we would expect the penguin with the longer bill to be about <span class="math inline">\(88.58\)</span>g more massive, on average.</li>
<li><strong>Using the Estimate:</strong> For each additional millimeter of bill length, we expect a penguin to have about <span class="math inline">\(88.58\)</span>g more mass, on average.</li>
<li><strong>Using Confidence Interval for the Estimate:</strong> For each additional millimeter of bill length, we expect a penguin to have somewhere between <span class="math inline">\(73.74\)</span>g and <span class="math inline">\(103.42\)</span>g more mass, on average.</li>
</ul>
<p>We could make similar interpretations from the model using flipper length to predict body mass. Try it!</p>
<p><strong>Warning:</strong> Inferences like these interpretations of our model coefficients are only valid if our regression assumptions are satisfied. As a reminder, those assumptions are:</p>
<ul>
<li>All of our observations are independent. (<strong>independence</strong>)</li>
<li>Our observations come from a random sample which is representative of the population. (<strong>representative sample</strong>)</li>
<li>The relationship between our response variable and the predictor variable is truly linear. (<strong>linearity</strong>)</li>
<li>The standard error of the residuals (our model’s prediction errors) is constant and does not depend on the value of the predictor variable. (<strong>homoscedasticity</strong>)</li>
<li>For any fixed value of the predictor variable, the values of the response in the population are normally distributed. (<strong>normality</strong>)</li>
</ul>
<hr>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>There’s a lot of information in this notebook, but here’s a recap of the most important items.</p>
<ul>
<li><p>Global model performance metrics (<code>fitted_model %&gt;% glance()</code>)</p>
<ul>
<li><p>The <code>p.value</code> is associated with a global test for model utility. This is a hypothesis test asking whether any of the predictor terms in the model have non-zero coefficients. For simple linear regression, we only have one predictor term, so the hypotheses are <span class="math inline">\(\begin{array}{lcl} H_0 &amp; : &amp; \beta_1 = 0\\ H_a &amp; : &amp; \beta_1 \neq 0\end{array}\)</span>.</p></li>
<li><p>For simple linear regression, the <code>r.squared</code> value measures the proportion of variation in the response which is explained by our model. (For multiple linear regression, we’ll look to <code>adj.r.squared</code> for this instead)</p>
<ul>
<li>Values closer to <span class="math inline">\(1\)</span> are better, but we should be skeptical of values too close to <span class="math inline">\(1\)</span>.</li>
</ul></li>
<li><p>The <code>sigma</code> value estimates the <em>residual standard error</em> for our model’s predictions.</p>
<ul>
<li>Lower values are better here.</li>
<li>While biased, we can use <code>sigma</code> to estimate how accurate we might expect our predictions to be. With approximately 95% confidence, our predictions are accurate to within <span class="math inline">\(\pm 2\)</span><code>sigma</code>.</li>
</ul></li>
</ul></li>
<li><p>Metrics for individual model terms (<code>fitted_model %&gt;% extract_fit_engine() %&gt;% tidy()</code>)</p>
<ul>
<li><p>The <code>estimates</code> column gives the estimated model coefficients (the estimated <span class="math inline">\(\beta\)</span> values).</p></li>
<li><p>The <code>std.error</code> column gives the estimate of the standard error for each model coefficient.</p></li>
<li><p>The <code>p.value</code> column gives the <span class="math inline">\(p\)</span>-value associated with a test asking whether the coefficient corresponding to the predictor model term (predictor variable) is non-zero.</p>
<ul>
<li>In the case of simple linear regression, this is the same as the <em>global test for model utility</em> because there is only one model term containing a predictor.</li>
</ul></li>
</ul></li>
<li><p>Unbiased estimates for <em>future</em> model performance (<code>fitted_model %&gt;% augment(test_data) %&gt;% metric(truth, .pred)</code>)</p>
<ul>
<li>We need to evaluate our model on unseen/hidden data to get an unbiased estimate of model performance.</li>
<li>For now, we’ll use the <em>test</em> data for this but we’ll soon see real problems associated with that approach. We’ll find something better to do instead!</li>
</ul></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>